language: c
script: make && make test # no ./configure

# Uncomment me if this gets annoying
#
# notifications: 
#   email: false 

addons:
  apt:
    sources:
    # precise, which is the default, doesn't have an official libuv1 package
    - sourceline: 'deb http://us.archive.ubuntu.com/ubuntu/ xenial universe'
    #
    packages:
    - libgmp3-dev
    - libsigsegv-dev
    - openssl
    - libssl-dev
    - libncurses5-dev
    - make
    - exuberant-ctags
    - libuv1-dev
    - g++
    - ragel
    - cmake
    - re2c
    - libcurl4-gnutls-dev
    - python
